### ISSUE TITLE
Persistent mode

### ISSUE THREAD

**Issue by Limbo95** [Arkensor/DayZCommunityOfflineMode#135]
I know there are probably many people asking this already, but are you thinking of creating another persistent mode, or a way to save your character? I'm just curious to know if it will be implemented or not as I follow this thread in the hopes my dream of a Dayz single player offline experience.

**Comment by S4MT3K** [comment]
In the batch file, witch you start the server with, theres a bunch of code that erases the storage_1 folder which means, that you always start with a new char and a wiped server. This is supposed to, to reduce performance impacts, errors, and missplaced objects. But if youreally want a persistance server, delete the part with the storage_1. (RD /s /q "storage_-1" > nul 2>&1)

**Comment by Limbo95** [comment]
Hi, 
I've tried that and I get an error message saying "Windows cannot find 'DayZ_64.exe"
Do you know where I have gone wrong? I deleted   /TRD /s /q "storage_1" nul 2>&1cd

**Comment by Limbo95** [comment]
Or is it just the ( "storage_1" to be deleted??

**Comment by S4MT3K** [comment]
`@echo off

taskkill /F /IM DayZ_x64.exe /T


cd ../../

start DayZ_x64.exe -mission=.\Missions\DayZCommunityOfflineMode.ChernarusPlus -scrAllowFileWrite -nosplash -noPause -noBenchmark -scriptDebug=true -filePatching -doLogs
`


NOTE: THIS BATCH HAS TO BE INSIDE OF FOLLOWING FOLDER:

"DayZCommunityOfflineMode.ChernarusPlus" 

EXAMPLE: §YOURSAVEDIRECTORY\Missions\DayZCommunityOfflineMode.ChernarusPlus

Otherwise it wont find the .exe because he goes back 2 times after taskkilling and erasing storage... thats the cd../ cd../ for... so he will end up in ROOTFOLDER and THEN executes DayZ. So make Sure this is in The Right Spot :D

Greetz S4MT3K

**Comment by Limbo95** [comment]
I am probably annoying you with this, but by changing the batch file, it still doesn't create a persistent mode on the offline game. I'm probably doing something wrong. But thanks for all the help!

**Comment by S4MT3K** [comment]
What error Occurs then?

**Comment by Limbo95** [comment]
So I deleted what was in the batch file and replaced it with what you sent previously, the game itself runs but there is no persistence, the character resets. I keep starting fresh. I've never played around with game files to know what the exact steps I need to take to ensure I do it correct. Just enjoyed the game and wanted to play offline and alone

**Comment by S4MT3K** [comment]
If you afraid of beeing killed. I can offer you our server. PVE Only... But not Online yet because of Major issues. If you havnt bought it... BUY IT :D Add me on Steam [BB] S4MT3Kツ (Same pic as here)

Back to your issue:

I havent tested it before, but youre right. It resets the char. so its apparently a createhive thing. It also doesnt touches the data in storage_1 anymore after created (as what i saw).

So i cant help you furthermore, i have to set up my server. but the offer stands if you want... Kill,rub, or any harming results in a perm ban...

Greetz S4MT3K

**Comment by Limbo95** [comment]
I'd like to join the server once you have set it up, thank you. Will add
you as soon as I am able. Thanks again for all the help

**Comment by lonewolfss** [comment]
when will the persistance save the map items that get placed as its very hard to keep placing al items to change something or add items to a made area
