### ISSUE TITLE
How can I add mods to this?

### ISSUE THREAD

**Issue by KhalMika** [Arkensor/DayZCommunityOfflineMode#266]
Hey there. I saw on reddit that you can just add " -mod=@mod1;@mod2;etc" at the end of the command lines in the batch file. But it's just not working or I don't know how do add them.
I already downloaded the mods and they're on my "workshop" folder on steam. Should I copy every mod on the missions folder? addons folder? I can't make them work :(

**Comment by johnstonecooper484** [comment]
I can help you tomorrow with this know you have to download the folder what the thing as you download then you have to place it inside another area it works on the offline community mod mode and allows you to become an admin fly around spawn things get the name and location you can extract it you can use this tool for PC or getting item names in location for consul

**Comment by johnstonecooper484** [comment]
Um I will try to see if I can get you the area at know it's too late at night for me right now so I will be open home sometime around noon right now it is 1007 for me at night I live in Iowa I will get you photos links and all talk and walk you through it so that it will work it's different for people on windows 7 and below if you have windows 10 it's a simple thing of just opening the location putting it in the right folder making a shortcut sang run as admin

**Comment by johnstonecooper484** [comment]
Try following this youtuber if you can't get it to work hit me up and let me know and I will try to help you https://youtu.be/UxqBLcKG5sc
