### ISSUE TITLE
add this features to offical offline mode

### ISSUE THREAD

**Issue by Bircko** [Arkensor/DayZCommunityOfflineMode#5]
would it be possible to add this features to offical offline mode?

**Comment by neonoxd** [comment]
official mode has loot spawns now

**Comment by neonoxd** [comment]
oh, it might just be me, i saw sada playing official offline looting guns on nwaf, I couldn't find any in your mission. i have no idea now tbh :D

**Comment by neonoxd** [comment]
your mission file only has the init.c. didn't check it before the update but now the official dayzOffline.ChernarusPlus has some scripts and loot related stuff

**Comment by Arkensor** [comment]
Thank you, and yes I hopefully finish my rework so that either the whole community offline mode is based on a patched version of the offical mission, or that you at least have all benefits from the official mission, and only need to patch the dta/scripts.pbo for things like no fall damage, infinite sprint etc

I'll see what I can come up with.

**Comment by Arkensor** [comment]
Next update will be based on the official mode
