### ISSUE TITLE
Free camera not working properly.

### ISSUE THREAD

**Issue by ExacoMvm** [Arkensor/DayZCommunityOfflineMode#71]
Hello, i've triggered once the orbit option, but later i didn't found a way for it to work, i've tried to change the controls etc.. anyway here's the commands that don't work:  https://i.gyazo.com/5da1abdaae29fded445f0f355ffbd0e9.png

Another issue: Player cannot raise weapon when in free camera. ( but it can shoot if i turn on free cam while holding RMB )

**Comment by DannyDog** [comment]
Did you try middle click to target camera? Thats what it should be instead of [Return]. Orbital mode and Follow cam modes will only work when a target object or position is selected (middle click). Also the next major update will refactor keybinds which will allow you to raise weapon when in free camera. Hold on tight :)
